apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - image: client-kubernetes-app:latest
        name: container1
        imagePullPolicy: IfNotPresent
